### ISSUE TITLE
Implement A Hamburger Menu Component

### ISSUE THREAD

**Issue by Oshioke-Salaki** [horuslabsio/seamlessui#8] opened 2024-09-26 00:17 UTC
Description:
Develop a fully functional Hamburger Menu component as per the design provided in the [FIGMA FILE](https://www.figma.com/design/pL9HcD5saTR6TtMsZYyS7z/STARKNET-UI-KITS?node-id=0-1&node-type=canvas&t=gT1lFVCNijoXRGlC-0) along with all it’s variants. The component showcases an all in one pop up for transaction tracker, network switcher, add token etc.

Requirements:

•⁠  ⁠Design: Follow the provided Figma design precisely for both light and dark mode. Ensure that the component is fully responsive across different screen sizes.
•⁠  ⁠Style Guide: Adhere strictly to the project’s existing style guide for consistency in UI and UX.
•⁠  ⁠Functionality: The component should be fully functional, allowing users to seamlessly switch networks.

After building the component, create a sub-route in the preview route for the component and display each of it’s variant for easy testing. 

Guidance:
There is an already implemented Connect Button component which can serve as a reference for styling, functionality and previewing.

Note:
No other external dependencies should be installed other than the ones already provided.

**Comment by Iwueseiter** [comment] 2024-09-26 00:17
H

**Comment by petersdt** [comment] 2024-09-26 00:18
@Oshioke-Salaki

**Comment by martinvibes** [comment] 2024-09-26 00:18
g

**Comment by CollinsC1O** [comment] 2024-09-26 00:18
a

**Comment by NueloSE** [comment] 2024-09-26 00:19
@Oshioke-Salaki  kindly assign me

**Comment by dev-chinx** [comment] 2024-09-26 00:22
hello @Oshioke-Salaki i am a frontend dev and blockchain developer
please can i work on this issue :) and would love to be a contributor

**Comment by Dprof-in-tech** [comment] 2024-09-26 00:40
Hey chief @Oshioke-Salaki  would love to contribute to this project by working on this issue.
Here is the link to my onlydust public profile.

https://app.onlydust.com/u/Dprof-in-tech

**Comment by Benjtalkshow** [comment] 2024-09-26 04:18
Hello @Oshioke-Salaki,
I’m Benjamin, a JavaScript developer with 4 years of experience and over 18 contributions on [OnlyDust. ](https://app.onlydust.com/u/Benjtalkshow)I specialize in building responsive and intuitive user interfaces. Here’s how I plan to approach the Hamburger Menu component:

My Approach:

1. I’ll start by thoroughly going through the Figma design to understand all the details and ensure everything looks great in both light and dark modes. I’ll make sure it’s fully responsive so it works smoothly on any screen size.

2. I’ll create the component (HamburgerMenu.tsx) with all the features like the transaction tracker, network switcher, and add token option. I’ll make sure it’s modular so future updates or changes can be made easily.

3.I’ll stick closely to the project’s style guide to keep everything consistent. For responsiveness, I’ll use CSS (likely Tailwind if that’s the project setup) to ensure it looks great on both mobile and desktop.

4.I’ll make sure the component works perfectly in both light and dark modes, switching seamlessly between them using the project’s existing theme logic.

5.I’ll ensure the network switcher works flawlessly, along with features like the transaction tracker and add token functionality. Everything will be intuitive and user-friendly.

6. Once it’s built, I’ll create a sub-route under /preview to display all the different variants of the menu, making it easy to test and review then I’ll make sure the code is clean, passes all project standards, and works across different browsers and screen sizes. I’ll also test it on various devices to ensure everything runs smoothly.

**Comment by Ayoazeez26** [comment] 2024-09-26 05:25
Hi @Oshioke-Salaki I will like to work on this.

I would follow the figma file design and produce pixel perfect implementation. This component enables a user to change the language, explorer and theme of the dapp.

I will use the dark: utitlity class in tailwind to implement dark mode, and also ensure that the component is fully responsive across screen sizes.
I would also follow the project's existing style guide for consistency.
ETA - 48HOURS

**Comment by Oshioke-Salaki** [comment] 2024-09-26 07:02
Hello guys, everyone needs to apply for issues via, The OnlyDust Platform. So please do that and i will assign. Only applications done via OD will be considered.

**Comment by Dprof-in-tech** [comment] 2024-09-26 07:30
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-scaffold).

### My background and how it can be leveraged
Hey chief,

I am Dprof-in-tech, an experienced Full Stack Blockchain Developer and I am excited to contribute my skills to the {project name} project in this ODHACK 8. With a strong background in Next.js, TypeScript, JavaScript, React, Node.js, Rust and Cairo, I've honed my technical skills across the blockchain development landscape.

My journey with OnlyDust began at Edition 2, and I've since made 34 contributions across 11 projects. This extensive experience on the platform has allowed me to develop a keen understanding of delivering high-quality solutions under tight deadlines.

Due to my web2 experience, i am skilled in building out pixel perfect UI components. I would love to contribute to this project by solving this issue.
Below is a link to my OnlyDust public profile.
https://app.onlydust.com/u/Dprof-in-tech


### How I plan on tackling this issue
Approach for Developing a Fully Functional Hamburger Menu Component:

I will analyze the Figma design and project style guide:
I will begin by thoroughly reviewing the Figma design for both light and dark mode to ensure a pixel-perfect implementation.
I will also refer to the project’s existing style guide to maintain consistency in fonts, colors, and other UI elements across the component.

I will set up the Hamburger Menu structure:
I will create the base structure for the Hamburger Menu using React, ensuring that it accommodates the various features outlined (transaction tracker, network switcher, add token, etc.).
I will ensure that each feature is housed inside the pop-up component, making it easy to navigate through the different functionalities.

I will ensure full responsiveness:
I will implement responsive styling using the existing styling framework (e.g., Tailwind CSS) to ensure that the Hamburger Menu adapts to different screen sizes, including mobile, tablet, and desktop.
The menu will include touch-friendly elements for smaller devices, and I will test it across multiple viewports to verify its responsiveness.

I will implement theme support (light/dark mode):
I will incorporate support for both light and dark modes, adhering to the design specifications provided in the Figma file.
I will leverage existing theme switching logic (if any) or add necessary logic to toggle between the two modes within the component.

I will develop the functionality for network switching and other features:
I will integrate network switching within the Hamburger Menu, following the provided logic for handling user interactions. This functionality will allow users to seamlessly switch between networks.
Similarly, I will add other components such as the transaction tracker and the "Add Token" button, ensuring they work as intended and align with the project’s overall design and functionality standards.

I will reuse the existing Connect Button component for consistency:
I will use the Connect Button component as a reference for maintaining consistent styling and behavior within the Hamburger Menu. This will ensure that the new component matches the look and feel of existing UI components.

I will create a sub-route in the preview route for testing:
Once the component is built, I will set up a dedicated sub-route within the /preview path to showcase the various Hamburger Menu variants for easy testing.
This sub-route will allow developers and testers to switch between different states and modes (e.g., network switching, light/dark mode) to verify that each variant works as expected.

I will test the component extensively:
After development, I will thoroughly test the Hamburger Menu across different devices and screen sizes to ensure it is fully responsive and functional.
I will also verify that the component adheres to both light and dark modes and performs all actions (network switcher, transaction tracker, add token, etc.) without any issues.

I will submit the PR with screenshots and notes:
I will include screenshots of the component in both light and dark modes, as well as across different screen sizes, along with any relevant testing notes.
The PR will also contain a description of how to access the sub-route for testing each variant of the Hamburger Menu.

My expected time of delivery would be 2 days from the date of assignment.

**Comment by devcollinss** [comment] 2024-09-26 08:04
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-scaffold).

### My background and how it can be leveraged
My name is Collins Ikechukwu. I'm a full stack developer. Nextjs, Cairo, nodej, react.

### How I plan on tackling this issue
1. **Set Up the Component**: Create a new file, `HamburgerMenu.tsx`, in your components directory.

2. **Design Implementation**: Use the Figma design to create the layout. Ensure it supports both light and dark modes.

3. **Responsive Design**: Use CSS media queries or a responsive design library to make the menu fully responsive across various screen sizes.

4. **Functionality**:
   - Implement features for transaction tracking, network switching, and token addition.
   - Use state management to handle menu visibility and functionality seamlessly.

5. **Adhere to Style Guide**: Ensure the component follows the project's existing style guide for consistent UI and UX.

6. **Create Sub-route**: After building the component, set up a sub-route (e.g., `/preview/hamburger`) to display the different variants of the Hamburger Menu for testing.

7. **Reference Existing Components**: Look at the already implemented Connect Button component for guidance on styling and functionality.

8. **Testing**: Verify that the menu works correctly in both modes and across different devices.

**Comment by Luluameh** [comment] 2024-09-26 08:04
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-scaffold).

### My background and how it can be leveraged
I have a solid background in front-end development, particularly with TypeScript and React, which makes me well-equipped for building interactive components like a Hamburger Menu. I’ve worked extensively with Figma designs, ensuring pixel-perfect UI implementation while adhering to design systems for consistency. My experience with responsive design allows me to develop components that work seamlessly across different screen sizes and in both light and dark modes.

Additionally, I have built and customized various UI components, such as navigation menus, transaction trackers, and other interactive elements. I am well-versed in following a style guide to maintain a consistent look and feel across the application. Moreover, I have experience working with state management, handling network switching, and integrating components with different functionalities.

By leveraging these skills, I can ensure that the Hamburger Menu component is not only visually accurate but also functional and user-friendly.

### How I plan on tackling this issue
To implement the Hamburger Menu component, I would approach it in the following steps:

Review the Figma design: I would start by closely analyzing the Figma file to understand the layout, variants, and behavior of the component, ensuring I account for both light and dark modes. I would note any interactive elements such as transaction tracker, network switcher, and add token buttons.

Set up component structure: I would create the Hamburger Menu component using React and TypeScript, ensuring the structure supports dynamic changes like toggling between light and dark modes, opening and closing the menu, and handling different screen sizes for responsiveness.

Style according to the design: Using the existing style guide, I would apply the appropriate styles to the component, ensuring consistency across the app. For light and dark modes, I would leverage CSS variables or theming solutions (if one exists in the project) to ensure easy switching between themes.

Implement functionality: I would then integrate functionality for:

The transaction tracker to display ongoing or past transactions.
The network switcher to allow users to change networks seamlessly.
The add token functionality to let users manage their tokens.
Preview and test variants: Using the reference Connect Button component for guidance, I would implement a preview route and display all variants of the Hamburger Menu (e.g., opened/closed, different screen sizes). This would allow easy testing of each variant in the component's preview route.

Test for responsiveness and cross-browser compatibility: Finally, I would ensure the component works smoothly on different screen sizes and browsers, testing both light and dark modes.

**Comment by Solomonsolomonsolomon** [comment] 2024-09-26 08:35
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-scaffold).

### My background and how it can be leveraged
3+ years fullstack developer 

### How I plan on tackling this issue
Implement hamburger based on figma file,and I'll also endure responsiveness on different screen sizes

**Comment by ShantelPeters** [comment] 2024-09-26 08:48
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-scaffold).

### My background and how it can be leveraged
i am a blockchain developer and i am available to work please

### How I plan on tackling this issue
To approach this problem :

1. Design & Style: Follow the Figma design exactly for both light and dark modes. Use the Connect Button component for consistency and reference. Ensure it's responsive for all screen sizes.

2. Functionality: Implement a fully functional Hamburger Menu that handles transaction tracking, network switching, and adding tokens. Ensure seamless functionality for all interactions.

3. Sub-Route: Create a sub-route in the preview for testing and displaying all menu variants.

4. No New Dependencies: Stick to existing dependencies, adding no new ones.

**Closed** 2024-10-03 13:02 UTC
Labels: ODHack8
