### ISSUE TITLE
Implement Add Token Button and Form Components

### ISSUE THREAD

**Issue by Oshioke-Salaki** [horuslabsio/seamlessui#4] opened 2024-09-25 23:03 UTC
## Description
Develop a fully functional Add token and form components as per the design provided in the [FIGMA FILE](https://www.figma.com/design/pL9HcD5saTR6TtMsZYyS7z/STARKNET-UI-KITS?t=gT1lFVCNijoXRGlC-0) along with all it’s variants. The button  pops open a form for adding new tokens to a connected wallet.

## Requirements

- Design: Follow the provided Figma design precisely for both light and dark mode. Ensure that the component is fully responsive across different screen sizes.
- Style Guide: Adhere strictly to the project’s existing style guide for consistency in UI and UX.
- Functionality: The component should be fully functional, allowing users to seamlessly switch networks.

After building the component, create a sub-route in the `preview` route for the component and display each of it’s variant for easy testing. 

## Guidance
There is an already implemented Connect Button component which can serve as a reference for styling, functionality and previewing.

## Note
No other external dependencies should be installed other than the ones already provided.

**Comment by Jemiiah** [comment] 2024-09-25 23:03
I

**Comment by CollinsC1O** [comment] 2024-09-25 23:06
@Oshioke-Salaki I will love to work on this

**Comment by dev-chinx** [comment] 2024-09-25 23:22
hello @Oshioke-Salaki i would love to work on this issue :)

**Comment by Kaminar-i** [comment] 2024-09-25 23:31
please @Oshioke-Salaki can i be assigned this issue

**Comment by Oshioke-Salaki** [comment] 2024-09-25 23:41
@Jemiiah assigning this to you. 🚀

**Comment by Oshioke-Salaki** [comment] 2024-09-26 07:01
Hello guys, everyone needs to apply for issues via, The OnlyDust Platform. So please do that and i will assign. Only applications done via OD will be considered.

**Comment by Gift-Naomi** [comment] 2024-09-26 07:48
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-scaffold).

### My background and how it can be leveraged
I am a web3/frontend developer

### How I plan on tackling this issue
1. **Component Setup**: Build the "Add Token" button and form components according to the Figma design for both light/dark modes. Ensure responsiveness across screen sizes and maintain consistency with the style guide.

2. **Functionality**: Implement the form to allow adding new tokens to a connected wallet, with validation and network switching. Trigger the form modal when the "Add Token" button is clicked.

3. **Preview Route**: Create a sub-route under the preview route to display all variants of the form and button for easy testing and interaction.

**Comment by Jemiiah** [comment] 2024-09-26 08:01
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-scaffold).

### My background and how it can be leveraged
i would love to work on this issue

**Comment by devcollinss** [comment] 2024-09-26 08:11
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-scaffold).

### My background and how it can be leveraged
My name is Collins Ikechukwu. I'm a full stack blockchain developer developer.

### How I plan on tackling this issue
1. **Review Figma Design**: Examine the design details for the Add Token button and form in both light and dark modes.

2. **Reference Connect Button**: Use the existing Connect Button component for styling and functionality guidance.

3. **Develop Add Token Button**: Create the button that triggers the token addition form.

4. **Implement Form Component**: Build the form to collect necessary token information.

5. **Ensure Responsiveness**: Test the button and form across various screen sizes for responsiveness.

6. **Network Switching Functionality**: Incorporate seamless network switching capability.

7. **Create Preview Sub-route**: Establish a sub-route in the preview section to display all component variants.

8. **Follow Style Guide**: Maintain adherence to the project’s style guide for consistency in UI/UX.

9. **Test Functionality**: Conduct thorough testing to ensure all features work as intended before finalizing.

**Comment by ridwanalaps** [comment] 2024-09-26 08:13
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-scaffold).

### My background and how it can be leveraged
I am a frontend developer with 2 years experience building applications

### How I plan on tackling this issue
I will follow the figma design and implement to perfect detailing for both light and dark mode while also adhering to the project's existing style guide
I would make sure the component is fully functional

I will also create a sub-route in the preview route for the component and display each of it’s variant for easy testing.

**Comment by CollinsC1O** [comment] 2024-09-26 08:33
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-scaffold).

### My background and how it can be leveraged
I will love to work on this please @Oshioke-Salaki

**Comment by ShantelPeters** [comment] 2024-09-26 08:38
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-scaffold).

### My background and how it can be leveraged
I am a frontend and blockchain developer with vast experience in css, javascript, typescript,,cario,react just to name a few. please i will love to be assigned to this issue

### How I plan on tackling this issue
To approach the problem i will do the following:

1.Design Implementation: Follow the Figma file precisely, ensuring the add token and form components align with both light and dark mode designs. Use the existing Connect Button as a style and functionality reference.
2.Responsiveness: Use responsive design techniques (media queries, flexbox, grid) to ensure the component looks good on different screen sizes.
3.Functionality: Implement the token addition logic, ensuring users can switch networks smoothly. Use the project's existing hooks and methods for wallet interaction.
4.Sub-Route: Create a sub-route in the preview section to showcase all variants of the component for easy testing.
5.No New Dependencies Stick to the existing dependencies to maintain consistency and avoid bloating the project.

**Closed** 2024-10-04 06:22 UTC
Labels: ODHack8
