### ISSUE TITLE
Implement A Leaderboard Component

### ISSUE THREAD

**Issue by Oshioke-Salaki** [horuslabsio/seamlessui#10] opened 2024-09-26 09:00 UTC
## Description:
Develop a fully functional leaderboard component as per the design provided in the [FIGMA FILE](https://www.figma.com/design/pL9HcD5saTR6TtMsZYyS7z/STARKNET-UI-KITS?node-id=0-1&node-type=canvas&t=gT1lFVCNijoXRGlC-0) along with all it’s variants.

## Requirements

•⁠  ⁠Design: Follow the provided Figma design precisely for both light and dark mode. Ensure that the component is fully responsive across different screen sizes.
•⁠  ⁠Style Guide: Adhere strictly to the project’s existing style guide for consistency in UI and UX.
•⁠  ⁠Functionality: The component should be fully functional, allowing users to seamlessly switch networks.

After building the component, create a sub-route in the ⁠ preview ⁠ route for the component and display each of it’s variant for easy testing. 

## Guidance
There is an already implemented Connect Button component which can serve as a reference for styling, functionality and previewing.

## Note
No other external dependencies should be installed other than the ones already provided.

**Comment by Jemiiah** [comment] 2024-09-26 09:01
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-scaffold).

### My background and how it can be leveraged
i

**Comment by Calebux** [comment] 2024-09-26 09:01
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-scaffold).

### My background and how it can be leveraged
I am good with FE

**Comment by Iwueseiter** [comment] 2024-09-26 09:02
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-scaffold).

### My background and how it can be leveraged
can I work on this?

**Comment by od-hunter** [comment] 2024-09-26 09:04
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-scaffold).

### My background and how it can be leveraged
Please can you assign this issue to me?

**Comment by Otaiki1** [comment] 2024-09-26 09:09
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-scaffold).

### My background and how it can be leveraged
Hi I am a blockchain developer with 3 years experience.  I have experience building components for applications, as i have built leaderboard components for several dapps

### How I plan on tackling this issue
I would ensure i follow the figma file to detail and test it to ensureit works as it should

**Comment by CollinsC1O** [comment] 2024-09-26 09:12
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-scaffold).

### My background and how it can be leveraged
Hello @Oshioke-Salaki can I take on this

**Comment by rishabhguptareal** [comment] 2024-09-26 09:15
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-scaffold).

### My background and how it can be leveraged
I am learner who builts awesome frontend and had done internship at geeks for geeks (one of the biggest cs portal by indian) .I have already written the necessary code for the leaderboard component and am eager to contribute to this project. assign me to this task, and I look forward to moving forward!

To develop the leaderboard component, I will first review the Figma design to understand its layout, typography, and color scheme, including the different variants for light and dark mode. After that, I will create a new React component for the leaderboard, making sure to follow the existing style guide for consistency in the user interface and experience. The Figma design will guide me in implementing the layout and colors, and I will ensure that the component is responsive across various screen sizes.

Next, I will add functionality to the leaderboard so that users can switch networks seamlessly. I’ll use the existing Connect Button component as a reference for styling and functionality. Finally, I will create a sub-route in the preview section for the leaderboard component, which will allow easy testing of each variant to ensure everything works as expected.

### How I plan on tackling this issue
To approach this problem, I will follow a structured method to ensure I understand the requirements and can provide a thorough solution. First, I’ll read the problem statement to grasp the goals and identify key components, like the leaderboard, Figma design, and style guide. I’ll also review existing references, such as the style guide and the Connect Button component, to gain a better understanding of the context.

I’ll break down the project into manageable tasks, including creating the leaderboard component, implementing its functionality, and setting up a sub-route for previewing it. I plan to research the Figma design and style guide to understand the layout, typography, and color scheme. 

Then, I will create a new React component for the leaderboard, using the style guide for consistency. I’ll make sure to implement the layout and colors as shown in the Figma design and ensure that the component is responsive across different screen sizes. After that, I will add the functionality that allows users to switch networks, using the Connect Button component as a reference.

I’ll create a sub-route in the preview section for the leaderboard component, allowing for easy testing of each variant. Once everything is implemented, I will test the component to ensure it meets all requirements and functions properly in both light and dark modes. I have already written the code for this, and I'm looking forward to getting assigned to contribute to this project!


I have already written the necessary code for the leaderboard component and am eager to contribute to this project. assign me to this task, and I look forward to moving forward!

**Comment by josephchimebuka** [comment] 2024-09-26 09:40
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-scaffold).

### My background and how it can be leveraged
Hello, I am Joseph I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. This is my first time to contribute to this repo ill appreciate the opportunity to contribute. this is a couple of frontend and blockchain projects i have built https://metacrypt.vercel.app/ https://mattedsgn.com/

### How I plan on tackling this issue
I will ensure the requirement are attained before submitting a PR and i will cnclude in 2-3 days

**Comment by martinvibes** [comment] 2024-09-26 09:54
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-scaffold).

### My background and how it can be leveraged
hello i am a frontend dev and blockchain developer
please can i work on this issue :) and would love to be a contributor



### How I plan on tackling this issue
Analyze the Design: Review the Figma file to understand how the leaderboard should look and function, including light and dark mode versions.

Follow the Style Guide: Make sure to use the existing style guide for consistent UI and UX throughout the project.

Build the Component:

Create the leaderboard according to the design specifications.
Ensure users can switch networks easily.
Make the component responsive so it looks good on all screen sizes.
Include All Variants: Develop different versions of the leaderboard as shown in the Figma design.

Set Up a Preview Route: Add a sub-route in the preview section of the app to display all variants of the leaderboard for testing purposes.

Use Existing Components as References: Look at the Connect Button component for guidance on styling and functionality.

Avoid Unnecessary Dependencies: Only use the libraries and dependencies that are already part of the project—don’t add new ones.

Test Everything: Ensure the leaderboard functions correctly and is visually appealing on different devices.

**Comment by ScottyDavies** [comment] 2024-09-26 09:54
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-scaffold).

### My background and how it can be leveraged
I have a strong background in front-end development with expertise in React and responsive design.

### How I plan on tackling this issue
To approach the development of the leaderboard component, I would:

 Review the provided Figma file to understand the layout and design requirements for both light and dark modes.

 Create the component structure in React, ensuring it’s responsive across different screen sizes.

 Use the existing style guide to apply consistent styling, referencing the Connect Button component for UI elements and functionality.

 Implement the network switching feature, ensuring it integrates smoothly with the overall application.

After completing the component, set up a sub-route in the preview route to display all variants for easy testing.

Test the component across various devices and screen sizes to ensure responsiveness and functionality.

**Comment by thesledge04** [comment] 2024-09-26 09:54
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-scaffold).

### My background and how it can be leveraged
My experience in developing UI components allows me to effectively translate design specifications into functional components while adhering to best practices.
Familiarity with Figma and design-to-code processes ensures that I can accurately implement the design while maintaining responsiveness and functionality.
I can leverage existing components as references to ensure consistency and efficiency in development.

### How I plan on tackling this issue
Analyze the Figma design for layout and variants.
Set up the component structure and styles based on the style guide.
Implement functionality for network switching.
Create a preview route to test the component.
Conduct testing and finalize adjustments.

**Comment by melnikga** [comment] 2024-09-26 10:00
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-scaffold).

### My background and how it can be leveraged
Can I take this? I’ve participated in almost every ODHack. I have extensive experience in frontend development. I can handle this task.



### How I plan on tackling this issue

My profile on OD: https://app.onlydust.com/u/melnikga

**Comment by Benjtalkshow** [comment] 2024-09-26 10:01
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-scaffold).

### My background and how it can be leveraged
 I'm Benjamin, a full-stack JavaScript developer, and I’m looking forward to building a fully functional leaderboard component based on the design from the Figma file. I have experience creating responsive and reusable components, and I’ve made 18 contributions since joining OnlyDust, so I’m pretty familiar with how things work here.

### How I plan on tackling this issue
My main focus will be to follow the Figma design closely, ensuring the component works well in both light and dark modes. I’ll make sure it’s fully responsive, so it looks great on all screen sizes. Plus, I’ll stick to our project’s style guide to keep everything consistent in terms of UI and UX.

The leaderboard needs to be functional too. I want to make it easy for users to switch networks without any hassle, enhancing their experience.

Once I’ve built the leaderboard, I’ll create a special sub-route in the preview section just for it. This way, each variant of the leaderboard can be displayed easily for testing, allowing us to see how everything functions.

I’ll be using the existing Connect Button component as a reference for styling and functionality, which should help keep things aligned with our project’s standards.

**Comment by MariangelaNM** [comment] 2024-09-26 10:02
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-scaffold).

### My background and how it can be leveraged
Hello, I'm Mariangela, a software developer specializing in front-end development. I have a passion for creating intuitive and dynamic user interfaces that enhance the user experience

### How I plan on tackling this issue
1. **Design Implementation**:
   - Follow the Figma design precisely for both light and dark modes.
   - Ensure the component is fully responsive across all screen sizes.

2. **Style Guide Adherence**:
   - Strictly adhere to the project’s existing style guide for consistent UI and UX.

3. **Functionality**:
   - Implement full functionality, including seamless network switching for users.

4. **Create Sub-Route**:
   - Add a sub-route under the `preview` route for the component.
   - Display each variant of the component within the sub-route for easy testing.

**Comment by ikemHood** [comment] 2024-09-26 10:04
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-scaffold).

### My background and how it can be leveraged
Hey @Oshioke-Salaki, i would love to get on this

### How I plan on tackling this issue
ETA 24hrs

**Comment by deeseeker** [comment] 2024-09-26 10:29
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-scaffold).

### My background and how it can be leveraged
Hi, I'm Qudus Adeyemi, a front-end developer with 2 years of experience specializing in React, TypeScript, and JavaScript, with a focus on building pixel-perfect and interactive user interfaces. In the previous OD Hackathon, I had the opportunity to contribute by improving the Starknet React documentation and developing a useWatchAssets hook for better wallet-tracking functionality. I enjoy learning new things and taking on challenges, and I see this issue as a valuable opportunity to further my knowledge of Web3 while contributing meaningfully to the Gostarkme project.

I estimate the task will take around 3-4 days to complete, and I'm eager to start and collaborate with the team!

### How I plan on tackling this issue
Clone the project
Follow the existing code patterns and improve the style where necessary.
Plan how to integrate the new page without breaking any existing functionality.
Review the provided Figma design and begin the conversion process.
Ensure the component is fully responsive, functional and interactive across all devices.
Test the implementation thoroughly and document any changes or improvements.

**Comment by mimisavage** [comment] 2024-09-26 10:37
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-scaffold).

### My background and how it can be leveraged
My name is Mirabel. I'm a full stack blockchain developer developer.

### How I plan on tackling this issue
To tackle this issue, here's a short description of my approach:

Study the Figma design:

Analyze both light and dark mode versions
Note all variants of the leaderboard component
Identify responsive design elements


Implement the component:

Create a new React component for the leaderboard
Use existing style guide and design system
Implement responsive design using CSS or Tailwind
Add functionality for network switching


Build variants:

Identify all required variants from the Figma file
Implement each variant as a separate component or use props for configuration


Create preview route:

Add a new sub-route under the 'preview' route
Display all variants of the leaderboard component
Ensure easy testing and interaction with each variant


Test and refine:

Verify functionality across different screen sizes
Test network switching feature
Ensure adherence to the style guide
Make any necessary adjustments for perfect design match

**Comment by sasasamaes** [comment] 2024-09-26 11:12
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-scaffold).

### My background and how it can be leveraged
JavaScript developer with 5+ years of experience involved in the full software development lifecycle. My experience includes providing IT solutions for enterprises using JavaScript, React, TypeScript, Node.js, and MongoDB. Additionally, I am expanding my knowledge in Web3 technologies, particularly in Cairo and Solidity.

I am also a community leader and sensei at Dev.f, where I mentor and lead a vibrant community of developers and am a Dojo Coding Member.

My areas of interest include Web3, frontend, backend, and full-stack development.

### How I plan on tackling this issue
I analyze the design in figma
I create the leaderboard page and page route
I create a list component that receives props
I create a pagination component
And I test.

**Comment by bhavyagosai** [comment] 2024-09-26 11:38
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-scaffold).

### My background and how it can be leveraged
Hey, I am Bhavya, a seasoned frontend engineer with two years of professional experience. I have been working with react, react native, nextjs, typescript, shadcn, tailwindcss for a while now and am familiar with the code. Have worked previously on Starknet Scaffold too!

### How I plan on tackling this issue
I have seen the figma file where the leaderboard is designed. Development for this task should be relatively easy and fast to do. A table with the UI and fonts and themes shown in the design would be used with the necessary columns. For the rankers, the relevant icon can be taken from the figma file for exact replication. Both light and dark themes will be made and separate testing/preview routes will be made for each display type (essentially themes here). 

As the issue is relatively easy, this can be done in ~1 day

**Comment by ShantelPeters** [comment] 2024-09-26 11:43
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-scaffold).

### My background and how it can be leveraged
I am blockchain developer , with strong background in javascript ,typescript etc

### How I plan on tackling this issue
To approach this problem, i will  begin by closely reviewing the provided Figma design for the leaderboard component, ensuring you understand all variants and requirements for light and dark modes. 

Next,i will implement the component following the design specifications while ensuring it is responsive across different screen sizes. Adhere to the existing style guide to maintain consistency.

**Closed** 2024-10-01 09:41 UTC
Labels: ODHack8
