### ISSUE TITLE
Implement An NFT Card Component

### ISSUE THREAD

**Issue by Oshioke-Salaki** [horuslabsio/seamlessui#6] opened 2024-09-25 23:15 UTC
## Description

Develop an  NFT Card component as per the design provided in the [FIGMA FILE](https://www.figma.com/design/pL9HcD5saTR6TtMsZYyS7z/STARKNET-UI-KITS?node-id=0-1&node-type=canvas&t=gT1lFVCNijoXRGlC-0) along with all it’s variants. The component shows NFT details, such as Name, collection, price, a button to view more details and buy now. 

`Tip`: The details can be passed as props.

## Requirements

•⁠  ⁠Design: Follow the provided Figma design precisely for both light and dark mode. Ensure that the component is fully responsive across different screen sizes.
•⁠  ⁠Style Guide: Adhere strictly to the project’s existing style guide for consistency in UI and UX.
•⁠  ⁠Functionality: The component should be fully functional, allowing users to seamlessly switch networks.

After building the component, create a sub-route in the ⁠ preview ⁠ route for the component and display each of it’s variant for easy testing. 

## Guidance
There is an already implemented Connect Button component which can serve as a reference for styling, functionality and previewing.

## Note
No other external dependencies should be installed other than the ones already provided.

**Comment by od-hunter** [comment] 2024-09-25 23:15
N

**Comment by Iwueseiter** [comment] 2024-09-25 23:15
H

**Comment by CollinsC1O** [comment] 2024-09-25 23:16
@Oshioke-Salaki I will love to work on this

**Comment by petersdt** [comment] 2024-09-25 23:16
h

**Comment by martinvibes** [comment] 2024-09-25 23:21
hello @Oshioke-Salaki i would love to work on this issue

**Comment by dev-chinx** [comment] 2024-09-25 23:23
hello @Oshioke-Salaki can i have this issue please

**Comment by ShantelPeters** [comment] 2024-09-25 23:23
Please can I be assigned to this issue @Oshioke-Salaki

**Comment by Kaminar-i** [comment] 2024-09-25 23:30
@Oshioke-Salaki i would love to work on this issue

**Comment by Ugo-X** [comment] 2024-09-25 23:50
Hello @Oshioke-Salaki I would love to be assigned to this.

Here is how i would handle it:


  

- **Step 1:** I will review the provided Figma design for the NFT Card to understand layout, colors, and styles for both light and dark modes. 

  

- **Step 2:** I will set up the basic structure of the component using React (or the relevant framework) and create the necessary props to receive NFT details (name, collection, price, etc.). 

  

- **Step 3:** I will implement the responsive design by using CSS media queries or a CSS-in-JS solution to ensure it displays correctly on various screen sizes. 

  

- **Step 4:** I will apply the project's existing style guide to maintain consistency in UI/UX. 

  

- **Step 5:** I will integrate the functionality that allows users to switch networks, ensuring this feature works seamlessly within the component. 

  

- **Step 6:** I will create a sub-route in the preview route to test the component and display all its variants for easy access. 

  

- **Step 7:** I will test the component thoroughly in both light and dark modes and across different devices to ensure everything functions as intended.

**Comment by Oshioke-Salaki** [comment] 2024-09-26 00:03
@od-hunter i will assign you 🚀

**Comment by Oshioke-Salaki** [comment] 2024-09-26 07:02
Hello guys, everyone needs to apply for issues via, The OnlyDust Platform. So please do that and i will assign. Only applications done via OD will be considered.

**Comment by Calebux** [comment] 2024-09-26 07:59
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-scaffold).

### My background and how it can be leveraged
I can jump on this as i have experience with FE

### How I plan on tackling this issue
To address the issue, I would take the following steps:

Analyze Figma Design:

Inspect layout, colors, fonts, spacing, and design specs for light/dark modes.
Identify NFT card variants (hover, selected states, different collections).
Define Props and State:

Decide on props (name, collection, price, image, network).
Manage internal state for light/dark mode and network switching.
Implement Card Structure:

Use HTML/CSS or a styling solution (styled-components, CSS modules).
Follow project style guide and utilize CSS variables for theme support.
Ensure responsiveness with media queries and layout techniques (CSS Grid/Flexbox).
Add Interaction Functionality:

Integrate network switching (using web3.js or ethers.js).
Reflect UI changes based on network selection (e.g., price updates).
Create Preview Route:

Set up a sub-route to display all NFT card variants for testing.
Verify layout and functionality across devices and themes.
Final Checks:

Ensure everything is functioning correctly.

**Comment by devcollinss** [comment] 2024-09-26 08:06
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-scaffold).

### My background and how it can be leveraged
My name is Collins Ikechukwu. I'm a full stack blockchain developer developer.

### How I plan on tackling this issue
1. **Set Up the Component**: Create a new file, `NFTCard.tsx`, in your components directory.

2. **Design Implementation**: Use the Figma design to structure the NFT card, ensuring it displays the name, collection, price, and buttons for more details and purchasing.

3. **Props for Data**: Pass NFT details (name, collection, price, etc.) as props to the component for flexibility and reusability.

4. **Responsive Design**: Ensure the card is fully responsive using CSS or a responsive design framework, adapting well to different screen sizes.

5. **Adhere to Style Guide**: Follow the existing style guide to maintain consistency in UI and UX throughout the application.

6. **Functionality**: Implement buttons that trigger appropriate actions (e.g., view details, buy now) while ensuring a smooth user experience.

7. **Reference Existing Components**: Use the Connect Button component for guidance on styling and functionality.

**Comment by CollinsC1O** [comment] 2024-09-26 08:34
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-scaffold).

### My background and how it can be leveraged
@Oshioke-Salaki can I work on this please

**Closed** 2024-10-01 09:45 UTC
Labels: ODHack8
